# Generated by Django 3.1.7 on 2021-03-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='china_treasury_yield',
            fields=[
                ('report_date', models.DateField(primary_key=True, serialize=False)),
                ('two_year', models.FloatField(blank=True, null=True)),
                ('five_year', models.FloatField(blank=True, null=True)),
                ('ten_year', models.FloatField(blank=True, null=True)),
                ('three_decade', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'china_treasury_yield',
                'managed': False,
            },
        ),
    ]
